### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by rom1504**
- make the example and test work by adding a very small test schematic (and cleanup .gitignore and .npmignore accordingly)
- use the new nbt.simplify to get rid of all the .value (fix bugs happening when some keys aren't there in the process)
- fix blocktype value for >128 : needed to convert from signed to unsigned (&0xff)

### CODE REVIEW

**Comment by rom1504** [comment]
Oh I just saw you have a `dev` branch. Is it ready to be used ? I see you added setBlock and some other useful things.

I guess it would have to be merged with this.

**Comment by 1b8** [comment]
Please switch the base branch to `dev` and discard the changes to the `.gitignore` and `.npmignore` files, as I have already made changes to those files in that branch.

The `dev` branch will be merged once the writing function, `schem.updateRaw()`, `entity.updateRaw()`, and `tileEntity.updateRaw()` work.

**Comment by rom1504** [comment]
I guess I'll rebase this when dev is merged ;)

**Comment by 1b8** [comment]
I will be adding a function that will be the opposite of `parse`, which will require a non-simplified version of the nbt.

So, the `raw` property of the schematic should be set to the un-simplified version, and the `_` property should be simplified.

**Comment by rom1504** [comment]
@1b8 sure, feel free to do that, I can rebase this later, or you can copy the changes into your dev branch if you want ;)

**Pull request merged**
